const ProfileElements = [
  {
    id: "name",
    label: "Name",
    placeholder: "Your organization's name",
    minimumLength: 5,
    errorMessage: "Name must be at least 5 characters long",
    type: "text",
  },
  {
    id: "firstName",
    label: "First Name",
    placeholder: "Your first name",
    minimumLength: 5,
    errorMessage: "First Name must be at least 5 characters long",
    type: "text",
  },
  {
    id: "lastName",
    label: "Last Name",
    placeholder: "Your last name",
    minimumLength: 5,
    errorMessage: "Last name must be at least 5 characters long",
    type: "text",
  },
  {
    id: "tagLine",
    label: "Tagline",
    placeholder: "A small and attractive tagline",
    minimumLength: 20,
    errorMessage: "Tagline must be at least 20 characters long",
    type: "text",
  },
  {
    id: "description",
    label: "About",
    placeholder: "Tell us about yourself",
    minimumLength: 100,
    errorMessage: "Bio must be at least 100 characters long",
    type: "textarea",
  },
  {
    id: "city",
    label: "City",
    placeholder: "The city where your organization is located",
    minimumLength: 3,
    errorMessage: "City must be at least 3 characters long",
    type: "text",
  },
  {
    id: "state",
    label: "State",
    placeholder: "The state where your organization is located",
    minimumLength: 3,
    errorMessage: "State must be at least 3 characters long",
    type: "text",
  },
  {
    id: "address",
    label: "Address",
    placeholder: "The address of your organization",
    minimumLength: 10,
    errorMessage: "Address must be at least 10 characters long",
    type: "text",
  },
  {
    id: "country",
    label: "Country",
    placeholder: "The country where your organization is located",
    minimumLength: 3,
    errorMessage: "Country must be at least 3 characters long",
    type: "text",
  },
  {
    id: "pincode",
    label: "Pincode",
    placeholder: "The pincode of your organization",
    minimumLength: 6,
    errorMessage: "Pincode must be at least 6 characters long",
    type: "text",
  },
];

export default ProfileElements;
