name: Other
description: Use this for any other issues. Please do NOT create blank issues
title: "[OTHER]"
labels:
  [
    "✨ goal: improvement",
    "🛠 status : under development",
    "🟨 priority: medium",
  ]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: "🥦 Browser"
      description: "What browser are you using ?"
      options:
        - Google Chrome
        - Brave
        - Microsoft Edge
        - Mozilla Firefox
        - Safari
        - Opera
        - Other
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you checked for similar open issues?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true

  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read the Contributing Guidelines?"
      options:
        - label: "I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)"
          required: true

  - type: dropdown
    attributes:
      label: Are you willing to work on this issue ?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - "Yes I am willing to submit a PR!"
        - "No, someone else can work on it"

  - type: markdown
    attributes:
      value: |
        Follow me on Twitter [here](https://twitter.com/mrTamall)
        Feel free to check out other cool repositories [here](https://github.com/IAmTamal)
